[instrument_info]
manufacturer='FEI'
model='DB'

[beam.ion.pinout]
scan_enable = "A0:1"
blank_enable = "A2:3"
blank = "A4#,A5"

[beam.electron.pinout]
blank = "A6:7"
scan_enable = "B0:1"

[transforms]
xflip = true
rotate90 = true

[timings]
# Scan Selector board uses TE 1462051-2 Relay
# Switching delay is 20 ms
ext_switch_delay_ms = 20