name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write
defaults:
  run:
    working-directory: software
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
      - run: pdm install -L pdm.dev.lock
      - run: pdm run docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: software/docs/build/html
          force_orphan: true