name: Run Unit Tests
on: 
<<<<<<< HEAD
    push:
        paths:
        - 'Gateware/*'
        - '.github/workflows/test.yml' # Trigger on changes to the workflow file
||||||| parent of 8c9e963 (experiment with a different python packaging structure)
  push:
    paths:
      - Gateware
=======
  push:
    # paths:
    #   - obi_applet
    #   - '.github/test.yml' # Trigger on changes to the workflow file
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.12"]  
  
    steps:  
      - name: Check out source code
        uses: actions/checkout@v3  
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate lockfile
        working-directory: ./obi_applet
        run: pdm lock --group test ${{ matrix.dep-versions == 'minimal' && '--strategy direct_minimal_versions' || '' }}
      - name: Install dependencies
        working-directory: ./obi_applet
        run: pdm sync  
      - name: Run tests  
        working-directory: ./obi_applet
        run: |  
          pdm run test
        
